name: Check Disabled Actions

on:
  workflow_call:
    outputs:
      should_continue:
        description: "Whether the current workflow should continue"
        value: ${{ jobs.check_disabled_actions.outputs.should_continue }}

jobs:
  check_disabled_actions:
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.check_status.outputs.should_continue }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check disabled actions
      id: check_status
      run: |
        set -x
        DIS_FILE=".github/workflows.disabled"
        ACT_FILE_NAME="`echo "${GITHUB_WORKFLOW_REF}" | sed 's|.*/workflows/\(.*\)\@refs/.*|\1|'`"
        if [ -f "${DIS_FILE}" ]; then
          SHOULD_CONTINUE="`grep -Fxq "${ACT_FILE_NAME}" "${DIS_FILE}" && echo "false" || echo "true"`"
        else
          SHOULD_CONTINUE="true"
        fi
        echo "should_continue=${SHOULD_CONTINUE}" >> $GITHUB_OUTPUT
