# This is a basic workflow to help you get started with Actions

name: Clean Build

# Controls when the action will run. 
on:
  # Triggers the workflow on all push or pull request events
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      COMPILER: ${{ matrix.compiler }}

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
        compiler: ['gcc', 'clang', 'gcc-9', 'gcc-10', 'clang-9', 'clang-10']
        include:
          - os: ubuntu-18.04
            compiler: 'gcc-i386-cross'
          - os: ubuntu-18.04
            compiler: 'clang-i386-cross'
          - os: ubuntu-18.04
            compiler: 'gcc-mips64-cross'
          - os: ubuntu-18.04
            compiler: 'gcc-arm32-cross'
          - os: ubuntu-18.04
            compiler: 'gcc-arm64-cross'
          - os: ubuntu-22.04
            compiler: 'gcc'
          - os: ubuntu-22.04
            compiler: 'clang'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: before_install
        run: sudo -H DEBIAN_FRONTEND=noninteractive apt-get update

      - name: install_depends
        run: sh -x scripts/build/install_depends.sh

      - name: script
        run: sh -x ./scripts/do-test.sh cleanbuild
