name: Push to DockerHub
on: [push, pull_request]

env:
  PLATFORMS: linux/amd64,linux/i386,linux/arm/v7,linux/arm64

jobs:
  check_disabled_actions:
    name: Check
    uses: ./.github/workflows/_check_disabled_actions.yml

  Docker:
    name: Build&Push to DockerHub
    needs: check_disabled_actions
    if: needs.check_disabled_actions.outputs.should_continue == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64,arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: sippylabs/rtpproxy

    # Cache the compiler cache
    - name: Cache the compiler cache
      uses: actions/cache@v3
      with:
        path: ccache
        key: dockerhub-ccache-${{ github.run_id }}
        restore-keys: |
          dockerhub-ccache

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile
        tags: |
          ${{ steps.meta.outputs.tags }}
          sippylabs/rtpproxy:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ env.PLATFORMS }}
        outputs: type=tar,dest=/tmp/ccache_export.tar

    - name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/Dockerfile.push
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          sippylabs/rtpproxy:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ env.PLATFORMS }}

    - name: Extract ccaches
      run: |
        rm -rf ccache
        tar --strip-components=2 --no-wildcards-match-slash --wildcards -x -f /tmp/ccache_export.tar "*/rtpproxy/ccache"
        du -d1 -h ccache
